### ISSUE TITLE
the pool asks for a password when it is started.

### ISSUE THREAD

**Issue by IB313184** [ilsawa/p2pool-cann#2]
the pool asks for a password when it is started.

I have all the downloaded bockchain and without errors, when I connect to the pool I request user an password

**Comment by ilsawa** [comment]
Sorry, I do not have time to teach you.
Find online instructions for working with the p2pool, for example:
[A Complete Guide to P2Pool - Merged Mining (BTC/NMC/DVC/IXC/I0C) plus LTC, Linux](https://bitcointalk.org/index.php?topic=62842.0)
[P2Pool - Bitcoin Wiki](https://en.bitcoin.it/wiki/P2Pool)
etc.
